import inquirer from 'inquirer';
import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { startBot } from './index.js';
import { authenticateWithWebService } from './auth.js';

interface EnvConfig {
  DISCORD_BOT_TOKEN: string;
  DISCORD_GUILD_ID: string;
  ANTHROPIC_API_KEY: string;
  LOG_LEVEL?: string;
  ARCHIVE_AFTER_DAYS?: string;
}

export async function run(): Promise<void> {
  console.log(chalk.cyan.bold('\n🤖 Cordbot - Discord Bot powered by Claude Code SDK\n'));

  const cwd = process.cwd();
  const envPath = path.join(cwd, '.env');

  // Check if .env exists in current directory
  if (!fs.existsSync(envPath)) {
    console.log(chalk.yellow('No .env file found in current directory.'));
    console.log(chalk.gray(`Current directory: ${cwd}\n`));

    // Use web service authentication flow
    const authResult = await authenticateWithWebService();

    if (!authResult) {
      console.log(chalk.red('\n❌ Authentication failed. Exiting.\n'));
      process.exit(1);
    }

    // Prompt for Claude API key and other config
    const config = await promptForConfiguration(authResult.botToken, authResult.guildId);

    // Write .env file
    const spinner = ora('Creating .env file...').start();
    writeEnvFile(envPath, config);
    spinner.succeed(chalk.green('.env file created successfully!'));

    console.log(chalk.gray(`\n📄 Configuration saved to: ${envPath}\n`));
  }

  // Load environment variables
  dotenv.config({ path: envPath });

  // Validate configuration
  const spinner = ora('Validating configuration...').start();
  const validation = validateConfig();

  if (!validation.valid) {
    spinner.fail(chalk.red('Configuration validation failed'));
    console.log(chalk.red('\n❌ Missing required environment variables:'));
    validation.missing.forEach(key => {
      console.log(chalk.red(`   - ${key}`));
    });
    console.log(chalk.yellow(`\nPlease update ${envPath} with the missing values.\n`));
    process.exit(1);
  }

  spinner.succeed(chalk.green('Configuration valid'));

  // Start the bot
  console.log(chalk.cyan('\n🚀 Starting Cordbot...\n'));
  await startBot(cwd);
}

async function promptForConfiguration(botToken: string, guildId: string): Promise<EnvConfig> {
  console.log(chalk.cyan('\n📝 Please provide your Claude API key:\n'));

  const answers = await inquirer.prompt([
    {
      type: 'password',
      name: 'ANTHROPIC_API_KEY',
      message: 'Anthropic API Key:',
      mask: '*',
      validate: (input) => {
        if (!input || input.trim().length === 0) {
          return 'Anthropic API Key is required';
        }
        if (!input.startsWith('sk-ant-')) {
          return 'Anthropic API Key should start with "sk-ant-"';
        }
        return true;
      },
    },
    {
      type: 'list',
      name: 'LOG_LEVEL',
      message: 'Log Level:',
      choices: ['info', 'debug', 'warn', 'error'],
      default: 'info',
    },
    {
      type: 'input',
      name: 'ARCHIVE_AFTER_DAYS',
      message: 'Archive inactive sessions after (days):',
      default: '30',
      validate: (input) => {
        const num = parseInt(input);
        if (isNaN(num) || num < 1) {
          return 'Must be a positive number';
        }
        return true;
      },
    },
  ]);

  return {
    DISCORD_BOT_TOKEN: botToken,
    DISCORD_GUILD_ID: guildId,
    ...answers,
  };
}

function writeEnvFile(envPath: string, config: EnvConfig): void {
  const lines = [
    '# Cordbot Configuration',
    '# Generated by cordbot agent',
    '',
    '# Discord Configuration',
    `DISCORD_BOT_TOKEN=${config.DISCORD_BOT_TOKEN}`,
    `DISCORD_GUILD_ID=${config.DISCORD_GUILD_ID}`,
    '',
    '# Anthropic Configuration',
    `ANTHROPIC_API_KEY=${config.ANTHROPIC_API_KEY}`,
    '',
    '# Optional Settings',
    `LOG_LEVEL=${config.LOG_LEVEL || 'info'}`,
    `ARCHIVE_AFTER_DAYS=${config.ARCHIVE_AFTER_DAYS || '30'}`,
    '',
    '# Security Note:',
    '# This file contains sensitive credentials. Never commit it to git!',
    '# It should be in your .gitignore file.',
  ];

  fs.writeFileSync(envPath, lines.join('\n'), 'utf-8');
}

function validateConfig(): { valid: boolean; missing: string[] } {
  const required = [
    'DISCORD_BOT_TOKEN',
    'DISCORD_GUILD_ID',
    'ANTHROPIC_API_KEY',
  ];

  const missing = required.filter(key => !process.env[key]);

  return {
    valid: missing.length === 0,
    missing,
  };
}
