import inquirer from 'inquirer';
import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { startBot } from './index.js';

interface EnvConfig {
  DISCORD_BOT_TOKEN: string;
  DISCORD_GUILD_ID: string;
  ANTHROPIC_API_KEY: string;
  CLAUDE_MODEL?: string;
  LOG_LEVEL?: string;
  ARCHIVE_AFTER_DAYS?: string;
}

export async function run(): Promise<void> {
  console.log(chalk.cyan.bold('\n🤖 ClaudeBot - Discord Bot powered by Claude Code SDK\n'));

  const cwd = process.cwd();
  const envPath = path.join(cwd, '.env');

  // Check if .env exists in current directory
  if (!fs.existsSync(envPath)) {
    console.log(chalk.yellow('No .env file found in current directory.'));
    console.log(chalk.gray(`Current directory: ${cwd}\n`));

    const { shouldConfigure } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'shouldConfigure',
        message: 'Would you like to configure ClaudeBot now?',
        default: true,
      },
    ]);

    if (!shouldConfigure) {
      console.log(chalk.red('\n❌ Configuration cancelled. Exiting.\n'));
      process.exit(0);
    }

    // Prompt for configuration
    const config = await promptForConfiguration();

    // Write .env file
    const spinner = ora('Creating .env file...').start();
    writeEnvFile(envPath, config);
    spinner.succeed(chalk.green('.env file created successfully!'));

    console.log(chalk.gray(`\n📄 Configuration saved to: ${envPath}\n`));
  }

  // Load environment variables
  dotenv.config({ path: envPath });

  // Validate configuration
  const spinner = ora('Validating configuration...').start();
  const validation = validateConfig();

  if (!validation.valid) {
    spinner.fail(chalk.red('Configuration validation failed'));
    console.log(chalk.red('\n❌ Missing required environment variables:'));
    validation.missing.forEach(key => {
      console.log(chalk.red(`   - ${key}`));
    });
    console.log(chalk.yellow(`\nPlease update ${envPath} with the missing values.\n`));
    process.exit(1);
  }

  spinner.succeed(chalk.green('Configuration valid'));

  // Start the bot
  console.log(chalk.cyan('\n🚀 Starting ClaudeBot...\n'));
  await startBot(cwd);
}

async function promptForConfiguration(): Promise<EnvConfig> {
  console.log(chalk.cyan('\n📝 Please provide the following configuration:\n'));

  const answers = await inquirer.prompt([
    {
      type: 'password',
      name: 'DISCORD_BOT_TOKEN',
      message: 'Discord Bot Token:',
      mask: '*',
      validate: (input) => {
        if (!input || input.trim().length === 0) {
          return 'Discord Bot Token is required';
        }
        return true;
      },
    },
    {
      type: 'input',
      name: 'DISCORD_GUILD_ID',
      message: 'Discord Guild (Server) ID:',
      validate: (input) => {
        if (!input || input.trim().length === 0) {
          return 'Discord Guild ID is required';
        }
        if (!/^\d+$/.test(input)) {
          return 'Discord Guild ID must be numeric';
        }
        return true;
      },
    },
    {
      type: 'password',
      name: 'ANTHROPIC_API_KEY',
      message: 'Anthropic API Key:',
      mask: '*',
      validate: (input) => {
        if (!input || input.trim().length === 0) {
          return 'Anthropic API Key is required';
        }
        if (!input.startsWith('sk-ant-')) {
          return 'Anthropic API Key should start with "sk-ant-"';
        }
        return true;
      },
    },
    {
      type: 'input',
      name: 'CLAUDE_MODEL',
      message: 'Claude Model (optional):',
      default: 'claude-sonnet-4-5-20250929',
    },
    {
      type: 'list',
      name: 'LOG_LEVEL',
      message: 'Log Level:',
      choices: ['info', 'debug', 'warn', 'error'],
      default: 'info',
    },
    {
      type: 'input',
      name: 'ARCHIVE_AFTER_DAYS',
      message: 'Archive inactive sessions after (days):',
      default: '30',
      validate: (input) => {
        const num = parseInt(input);
        if (isNaN(num) || num < 1) {
          return 'Must be a positive number';
        }
        return true;
      },
    },
  ]);

  return answers;
}

function writeEnvFile(envPath: string, config: EnvConfig): void {
  const lines = [
    '# ClaudeBot Configuration',
    '# Generated by claudebot CLI',
    '',
    '# Discord Configuration',
    `DISCORD_BOT_TOKEN=${config.DISCORD_BOT_TOKEN}`,
    `DISCORD_GUILD_ID=${config.DISCORD_GUILD_ID}`,
    '',
    '# Anthropic Configuration',
    `ANTHROPIC_API_KEY=${config.ANTHROPIC_API_KEY}`,
    '',
    '# Optional Settings',
    `CLAUDE_MODEL=${config.CLAUDE_MODEL || 'claude-sonnet-4-5-20250929'}`,
    `LOG_LEVEL=${config.LOG_LEVEL || 'info'}`,
    `ARCHIVE_AFTER_DAYS=${config.ARCHIVE_AFTER_DAYS || '30'}`,
    '',
    '# Security Note:',
    '# This file contains sensitive credentials. Never commit it to git!',
    '# It should be in your .gitignore file.',
  ];

  fs.writeFileSync(envPath, lines.join('\n'), 'utf-8');
}

function validateConfig(): { valid: boolean; missing: string[] } {
  const required = [
    'DISCORD_BOT_TOKEN',
    'DISCORD_GUILD_ID',
    'ANTHROPIC_API_KEY',
  ];

  const missing = required.filter(key => !process.env[key]);

  return {
    valid: missing.length === 0,
    missing,
  };
}
